import Foundation

public enum ClipboardKind: String, Codable, Sendable { case text, image }

public struct ClipboardPreferences: Codable, Equatable, Sendable {
    public var enabled = false
    public var paused = false
    public var maximumCount = 50
    public var maximumDays = 7
    public var maximumMegabytes = 200
    public var excludedBundleIDs: Set<String> = []

    public init() {}
    public var maximumBytes: Int { maximumMegabytes * 1_000_000 }
    public var isValid: Bool {
        (1...1_000).contains(maximumCount) && (1...365).contains(maximumDays)
            && (1...2_000).contains(maximumMegabytes)
    }
}

public enum ClipboardFailure: String, Error, Sendable {
    case storage, keyUnavailable, damagedEntry, tooLarge, unsupportedImage, writeFailed
}

public struct ClipboardContent: Equatable, Sendable {
    public static let maximumTextBytes = 1_000_000
    public static let maximumImageBytes = 20_000_000
    public let kind: ClipboardKind
    public let data: Data
    public let thumbnail: Data?
    public let sourceBundleID: String?
    public let sourceIsEstimated: Bool

    public init(kind: ClipboardKind, data: Data, thumbnail: Data? = nil,
                sourceBundleID: String? = nil, sourceIsEstimated: Bool = true) {
        self.kind = kind; self.data = data; self.thumbnail = thumbnail
        self.sourceBundleID = sourceBundleID; self.sourceIsEstimated = sourceIsEstimated
    }
    public var isValid: Bool {
        guard !data.isEmpty, (thumbnail?.count ?? 0) <= 1_000_000,
              (sourceBundleID?.utf8.count ?? 0) <= 1_024 else { return false }
        switch kind {
        case .text: return data.count <= Self.maximumTextBytes && String(data: data, encoding: .utf8) != nil
        case .image: return data.count <= Self.maximumImageBytes
        }
    }
}

public struct ClipboardRecord: Identifiable, Equatable, Sendable {
    public let id: UUID
    public let kind: ClipboardKind
    public let capturedAt: Date
    public let storedBytes: Int
    public init(id: UUID = UUID(), kind: ClipboardKind, capturedAt: Date, storedBytes: Int) {
        self.id = id; self.kind = kind; self.capturedAt = capturedAt; self.storedBytes = storedBytes
    }
}

public struct ClipboardEntry: Identifiable, Equatable, Sendable {
    public var id: UUID { record.id }
    public let record: ClipboardRecord
    public let text: String?
    public let thumbnail: Data?
    public let sourceBundleID: String?
    public let damaged: Bool

    public init(record: ClipboardRecord, text: String?, thumbnail: Data?, sourceBundleID: String?, damaged: Bool = false) {
        self.record = record; self.text = text; self.thumbnail = thumbnail
        self.sourceBundleID = sourceBundleID; self.damaged = damaged
    }
}

public enum ClipboardRetention {
    public static func retained(_ records: [ClipboardRecord], preferences: ClipboardPreferences, now: Date) -> [ClipboardRecord] {
        guard preferences.isValid else { return [] }
        let cutoff = now.addingTimeInterval(-Double(preferences.maximumDays) * 86_400)
        let live = records.filter { $0.capturedAt > cutoff }.sorted {
            $0.capturedAt == $1.capturedAt ? $0.id.uuidString < $1.id.uuidString : $0.capturedAt > $1.capturedAt
        }
        var bytes = 0
        var result: [ClipboardRecord] = []
        for record in live.prefix(preferences.maximumCount) {
            guard record.storedBytes >= 0, record.storedBytes <= preferences.maximumBytes - bytes else { break }
            bytes += record.storedBytes
            result.append(record)
        }
        return result
    }
}

public enum ClipboardPrivacy {
    public static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "org.nspasteboard.RestoredType",
        "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
        "Pasteboard generator type", "com.agilebits.onepassword"
    ]
    public static func shouldSkip(types: Set<String>, declaredSource: String?, foregroundSource: String?, exclusions: Set<String>) -> Bool {
        !types.isDisjoint(with: ignoredTypes)
            || declaredSource.map(exclusions.contains) == true
            || foregroundSource.map(exclusions.contains) == true
    }
}
